const SEAT_TYPE = {
  BUSINESS: "BUSINESS",
  ECONOMY: "ECONOMY",
  PREMIUM_ECONOMY: "PREMIUM_ECONOMY",
  FIRST_CLASS: "FIRST_CLASS",
};

const STATUS_TYPE = {
  BOOKED: "BOOKED",
  INITIATED: "INITIATED",
  CANCELLED: "CANCELLED",
  PENDING: "PENDING",
};

module.exports = {
  SEAT_TYPE,
  STATUS_TYPE,
};
